apiVersion: v1
kind: Secret
metadata:
  name: __SECRET_NAME__
  namespace: __NAMESPACE__
type: Opaque
stringData:
  encryption-provider-config.yaml: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: EncryptionConfiguration
    resources:
      - resources:
          - secrets
        providers:
          - aescbc:
              keys:
                - name: key1
                  secret: "__ENCRYPTION_KEY__"
          - identity: {}
